FROM phusion/baseimage:0.11

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN apt-get update -y && apt-get install -y \
    net-tools \
    iproute2 \
    iputils-ping \
    python3 \
    python3-pip

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /app
WORKDIR /app
COPY dvel/server.py /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt
